# Generated by Django 2.0.1 on 2018-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='id',
        ),
        migrations.AddField(
            model_name='moneda',
            name='symbol',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
